### ISSUE TITLE
app.vue报错

### ISSUE THREAD

**Issue by Mrcxt** [Vincent1993/V2EX-mobile#6]
![image](https://cloud.githubusercontent.com/assets/16064831/19679704/738ebab8-9ad5-11e6-912e-6952e403abee.png)
出现了这个问题，当然，我把plugin.js里面的vuex/logger改成了vuex/dist/logger，卡在这了o(╯□╰)o

**Comment by Vincent1993** [comment]
你更新下代码应该好了 然后重新装下依赖
